# Generated by Django 4.2 on 2025-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("image", models.ImageField(upload_to="blog")),
                ("date", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Блог",
            },
        ),
    ]
