# Generated by Django 4.2 on 2025-02-03 13:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
        migrations.AddField(
            model_name="blog",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
        migrations.AddField(
            model_name="blog",
            name="text1",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="text2",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
    ]
