# Generated by Django 4.2 on 2025-02-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_image1_blog_image2_blog_text1_blog_text2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Комментарий",
            },
        ),
    ]
