# Generated by Django 4.2 on 2025-01-27 12:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("description", ckeditor.fields.RichTextField()),
                ("title_cool", models.CharField(max_length=155)),
                ("description_cool", ckeditor.fields.RichTextField()),
                ("title_mussion", models.CharField(max_length=155)),
                ("image_mussion", models.ImageField(upload_to="settings")),
                ("title_team", models.CharField(max_length=155)),
                ("title_avenser", models.CharField(max_length=155)),
                ("title_works", models.CharField(max_length=155)),
                ("title_testimonials", models.CharField(max_length=155)),
                ("title_about", models.CharField(max_length=155)),
                ("title_contact", models.CharField(max_length=155)),
                ("title_have", models.CharField(max_length=155)),
                ("description_contact", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name_plural": "Настройка Главной Страницы",
            },
        ),
    ]
